apiVersion: v1
data:
  keyfile.enc: # keyfile.enc in base64 (See README.md)
  keyfile.key: # keyfile.key in base64 (See README.md)
kind: Secret
metadata:
  name: mariadb-data-secret
type: Opaque
---
apiVersion: v1
data:
  server.cert: # server-cert.pem in base64 (See README.md)
  server.key: # server-key.pem in base64 (See README.md)
  ca.cert: # ca.pem in base64 (See README.md)
kind: Secret
metadata:
  name: mariadb-replication-secret
type: Opaque
